=== tangbao/ECE568-Assignments-Archive/HW4/Q3/bib.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT bib ( (book | article | phd_theses)+)>
<!ELEMENT book ( author, title, year, (address)?, publisher )> 
<!ELEMENT article ( author, title, year, volume, page, journal) > 
<!ELEMENT phd_theses (author, title, year, university) >
<!ELEMENT page (from, to)>
<!ELEMENT author (first_name, last_name)>
<!ELEMENT first_name (#PCDATA) >
<!ELEMENT last_name (#PCDATA) >
<!ELEMENT title (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT journal (#PCDATA)>
<!ELEMENT volume (#PCDATA)>
<!ELEMENT university (#PCDATA)>

=== tangbao/ECE568-Assignments-Archive/HW4/Q3/bib.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="bib.xsl"?>
<!DOCTYPE bib SYSTEM "bib.dtd">

<bib> 
    <book>
        <author>Leslie Lamport</author>
        <title>Latex: A Document Preparation System </title> 
        <year>1986</year> 
        <publisher>Addison-Wesley</publisher>
    </book>
    <article>
        <author>David Marr</author>
        <title>Visual information processing</title> 
        <year>1980</year>
        <volume>290</volume>
        <page>
            <from>199</from>
            <to>218</to> </page>
        <journal>Phil. Trans. Roy. Soc. B</journal> 
    </article>
    <article>
        <author>R. K. Clifton </author>
        <title>Breakdown of echo suppression in the precedence
            effect</title> 
        <year>1987</year> 
        <volume>82</volume>
        <page> 
            <from>1834</from> 
            <to>1835</to>
        </page>
        <journal>J. Acoust. Soc. Am. </journal> 
    </article>
    
    <book>
        <author>David Marr</author> 
        <title>Vision</title> 
        <year>1982</year>
        <address> NY </address> 
        <publisher>Freeman</publisher>
    </book>
    <article>
        <author>David Marr</author>
        <title>Visual information processing</title> 
        <year>1980</year>
        <volume>290</volume>
        <page>
            <from>199</from>
            <to>218</to> </page>
        <journal> Phil. Trans. Roy. Soc. B</journal> 
    </article>
</bib>
