=== tangbao/ECE568-Assignments-Archive/HW4/Q1/q1a.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT products (product*)>
<!ELEMENT product (name, price, description, store*)>
<!ELEMENT store (name, phones, markup)>

<!ELEMENT name (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT phones (#PCDATA)>
<!ELEMENT markup (#PCDATA)>

<!ATTLIST product pid CDATA #REQUIRED>
<!ATTLIST store sid CDATA #REQUIRED>

=== tangbao/ECE568-Assignments-Archive/HW4/Q1/q1a.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE products SYSTEM "q1a.dtd">
<products>
    <product pid="p123">
        <name>gizmo</name>
        <price>22.99</price>
        <description>great</description>
        <store sid="s323">
            <name>Wiz</name>
            <phones>555-1234</phones>
            <markup>25%</markup>
        </store>
        <store sid="s323">
            <name>Wiz</name>
            <phones>555-1234</phones>
            <markup>15%</markup>
        </store>
    </product>
    <product pid="p231">
        <name>gizmoPlus</name>
        <price>99.99</price>
        <description>more features</description>
        <store sid="s323">
            <name>Wiz</name>
            <phones>555-1234</phones>
            <markup>10%</markup>
        </store>
    </product>
    <product pid="p312">
        <name>gadget</name>
        <price>59.99</price>
        <description>good value</description>
    </product>
</products>
